backend:
  name: git-gateway
  branch: master

site_url: https://mpowa.netlify.app/

media_folder: src/images
public_folder: src/markdown/news

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/markdown/news"
    create: true
    path: "/{{year}}-{{month}}"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
