backend:
  name: git-gateway
  branch: master

site_url: https://mlab-mpowa.netlify.app/

media_folder: static/images
public_folder: src/images

collections:
  - name: "blog"
    label: "Blog"
    folder: "_news"
    create: true
    path: "/{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Tags", name: "tags", widget: "map" }
      - { label: "Body", name: "body", widget: "markdown" }
